/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tu-router` | `/tu-router`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ataque` | `/ataque`; params?: Router.UnknownInputParams; } | { pathname: `/post-login`; params?: Router.UnknownInputParams; } | { pathname: `/nivel/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../data/levels`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post-login` | `/post-login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tu-router` | `/tu-router`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ataque` | `/ataque`; params?: Router.UnknownOutputParams; } | { pathname: `/post-login`; params?: Router.UnknownOutputParams; } | { pathname: `/nivel/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../data/levels`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/post-login` | `/post-login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tu-router${`?${string}` | `#${string}` | ''}` | `/tu-router${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ataque${`?${string}` | `#${string}` | ''}` | `/ataque${`?${string}` | `#${string}` | ''}` | `/post-login${`?${string}` | `#${string}` | ''}` | `/nivel/[id]${`?${string}` | `#${string}` | ''}` | `/../data/levels${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/post-login${`?${string}` | `#${string}` | ''}` | `/post-login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tu-router` | `/tu-router`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ataque` | `/ataque`; params?: Router.UnknownInputParams; } | { pathname: `/post-login`; params?: Router.UnknownInputParams; } | { pathname: `/nivel/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../data/levels`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/post-login` | `/post-login`; params?: Router.UnknownInputParams; };
    }
  }
}
